#!/usr/bin/env python3
"""
research.cerebro_export_detector — classify keyword exports and match them to
approved ASIN batches.

Phase 0 found three real shapes in the user's folders:
  CEREBRO_WITH_ASIN_RANKS  39 cols, Competitor Rank (avg) + N bare-ASIN columns  <- the gold input
  CEREBRO_PLAIN            15 cols, no ASIN columns, no competitor-rank fields
  XRAY_KEYWORD             9  cols, Competitor Rank (avg) but no ASIN columns

The spec's xray_keyword_rule (Keyword Phrase + Cerebro IQ + SV + Competitor Rank avg)
matches BOTH the 39-col and 9-col shapes, so it cannot be the discriminator. The only
reliable signal is the presence of ^B0[A-Z0-9]{8}$ columns.
"""
import os, re, glob

CEREBRO_WITH_ASIN_RANKS = "cerebro_with_asin_ranks"
CEREBRO_PLAIN           = "cerebro_plain_no_ranks"
XRAY_KEYWORD            = "xray_keyword_export"
PRODUCT_XRAY            = "product_xray_not_keywords"
GENERATED_LEGACY        = "generated_by_this_toolkit"
UNSUPPORTED             = "unsupported_or_malformed"

ASIN_COL = re.compile(r"^B0[A-Z0-9]{8}$")
OUR_OUTPUTS = ("master-keywords.xlsx", "asin-candidates.csv", "asin-candidates.json",
               "asin-batches.json", "cerebro-evidence-matrix.csv",
               "cerebro-evidence-matrix.json", "master-keywords-lean.xlsx")


def _norm(c):
    return re.sub(r"\s+", " ", str(c).replace("﻿", "").strip().lower())


def read_headers(path):
    import pandas as pd
    try:
        df = pd.read_csv(path, nrows=0) if path.lower().endswith(".csv") else pd.read_excel(path, nrows=0)
    except Exception:
        return None
    return [str(c) for c in df.columns]


def detect_keyword_export(path):
    """-> dict(kind, reason, columns, asin_columns)"""
    base = os.path.basename(path)
    if base.lower() in OUR_OUTPUTS:
        return {"kind": GENERATED_LEGACY, "reason": "generated by this toolkit — not a raw export",
                "columns": [], "asin_columns": []}
    cols = read_headers(path)
    if cols is None:
        return {"kind": UNSUPPORTED, "reason": "file could not be parsed", "columns": [], "asin_columns": []}
    low = {_norm(c) for c in cols}
    asins = [c for c in cols if ASIN_COL.match(str(c).strip())]

    if "keyword phrase" not in low and "keyword" not in low:
        if "asin" in low and ("product details" in low or "title" in low):
            return {"kind": PRODUCT_XRAY, "reason": "product Xray export, not a keyword export",
                    "columns": cols, "asin_columns": []}
        return {"kind": UNSUPPORTED, "reason": "no Keyword Phrase column", "columns": cols, "asin_columns": []}

    if asins:
        return {"kind": CEREBRO_WITH_ASIN_RANKS,
                "reason": f"Cerebro reverse-ASIN export with {len(asins)} individual ASIN rank columns",
                "columns": cols, "asin_columns": asins}
    if "competitor rank (avg)" in low and len(cols) <= 12:
        return {"kind": XRAY_KEYWORD, "reason": "Xray Keyword export (no per-ASIN ranks)",
                "columns": cols, "asin_columns": []}
    if "search volume" in low:
        return {"kind": CEREBRO_PLAIN,
                "reason": "Cerebro keyword export without per-ASIN rank columns",
                "columns": cols, "asin_columns": []}
    return {"kind": UNSUPPORTED, "reason": "keyword-like but missing Search Volume",
            "columns": cols, "asin_columns": []}


def classify_keyword_folder(path):
    files = [path] if os.path.isfile(path) else sorted(
        f for f in glob.glob(os.path.join(path, "*")) if f.lower().endswith((".xlsx", ".xls", ".csv")))
    out = []
    for f in files:
        d = detect_keyword_export(f)
        d.update({"file": os.path.basename(f), "path": f})
        out.append(d)
    return out


def load_approved_batches(folder):
    """Read ASIN-BATCHES.json (Phase 2 output). -> {batch_id: [asins]} or {}"""
    import json
    p = os.path.join(folder, "ASIN-BATCHES.json")
    if not os.path.exists(p):
        return {}
    try:
        d = json.load(open(p, encoding="utf-8"))
    except Exception:
        return {}
    return {b["batch_id"]: list(b.get("paste_ready_asins", [])) for b in d.get("batches", [])}


def match_export_to_batch(asin_columns, batches, min_overlap=0.5):
    """Match a Cerebro export to the approved batch it was produced from.

    Helium 10 names the file after the primary ASIN and omits it from the rank
    columns, so a 10-ASIN batch legitimately yields 9 columns. Missing expected
    ASINs are reported, never silently dropped.
    """
    obs = {str(a).strip().upper() for a in asin_columns}
    best = None
    for bid, asins in batches.items():
        exp = {a.strip().upper() for a in asins}
        if not exp:
            continue
        overlap = len(obs & exp)
        pct = overlap / len(exp)
        row = {"batch_id": bid, "expected": sorted(exp), "observed": sorted(obs),
               "overlap_count": overlap, "overlap_pct": round(100.0 * pct, 1),
               "missing_expected_asins": sorted(exp - obs),
               "unexpected_asins": sorted(obs - exp),
               "valid_asin_denominator": len(exp),
               "matched": pct >= min_overlap}
        if best is None or row["overlap_count"] > best["overlap_count"]:
            best = row
    if best is None:
        return {"batch_id": None, "matched": False, "overlap_pct": 0.0,
                "reason": "no approved ASIN-BATCHES.json to match against",
                "observed": sorted(obs), "expected": [], "missing_expected_asins": [],
                "unexpected_asins": sorted(obs), "valid_asin_denominator": len(obs) or 0}
    if not best["matched"]:
        best["reason"] = (f"only {best['overlap_pct']}% of {best['batch_id']} ASINs present — "
                          f"below the {int(min_overlap*100)}% minimum; not merged on Keyword Phrase alone")
    else:
        best["reason"] = f"matched {best['batch_id']} on {best['overlap_count']}/{best['valid_asin_denominator']} ASIN columns"
    return best
