#!/usr/bin/env python3
"""
research.export_detector — classify a Helium 10 export by its headers.

Fixes ASIN-005: the old loader read every .xlsx/.xls/.csv in a folder and
concatenated them, so Cerebro keyword rows became product candidates with
ASIN = nan. A file only enters product scoring when it is a product-level
Xray export; everything else is skipped with a recorded reason.

Header inspection only — no row scanning, so this stays cheap.
"""
import os, re

PRODUCT_XRAY  = "product_xray"
CEREBRO       = "skipped_keyword_export"
XRAY_KEYWORD  = "skipped_xray_keyword_export"
UNKNOWN       = "skipped_unrecognized"
UNREADABLE    = "skipped_unreadable"

# Product-market columns. A real Xray carries several of these; a keyword
# export carries none.
MARKET_COLS = ("asin sales", "asin revenue", "parent level sales", "parent level revenue",
               "bsr", "review count", "price", "fulfillment", "display order",
               "ratings", "seller", "creation date", "brand")


def _norm(c):
    return re.sub(r"[^a-z0-9]+", " ", str(c).replace("﻿", "").lower()).strip()


def read_headers(path):
    """Return the normalized header list, or None if the file cannot be read."""
    import pandas as pd
    try:
        if path.lower().endswith(".csv"):
            df = pd.read_csv(path, nrows=0)
        else:
            df = pd.read_excel(path, nrows=0)
    except Exception:
        return None
    return [_norm(c) for c in df.columns]


OUR_OUTPUTS = ("asin-candidates.csv", "asin-candidates.json", "asin-batches.json",
               "master-keywords.xlsx", "cerebro-batch-evaluation.json")


def detect_export_type(path):
    """-> (type, reason, headers). Order matters: keyword exports are ruled out first."""
    base = os.path.basename(path).lower()
    # Our own outputs carry asin/title/price columns and would re-enter as input,
    # inflating the pool with rows we just produced.
    if base in OUR_OUTPUTS:
        return UNKNOWN, "generated by this toolkit — not an input export", []
    h = read_headers(path)
    if h is None:
        return UNREADABLE, "file could not be parsed as CSV/XLSX", []
    has = lambda *names: any(n in h for n in names)

    # Xray Keyword export: keyword phrase + Cerebro IQ / competitor rank.
    if has("keyword phrase") and (has("cerebro iq score") or has("competitor rank avg")):
        return XRAY_KEYWORD, "Xray Keyword export (keyword rows, not products)", h
    # Cerebro/Magnet export: keyword phrase + search volume.
    if has("keyword phrase", "keyword") and has("search volume"):
        return CEREBRO, "Cerebro/Magnet keyword export (keyword rows, not products)", h

    # Product Xray: ASIN + a title + at least two market columns.
    if has("asin") and has("product details", "title"):
        n = sum(1 for c in MARKET_COLS if any(c == x or c in x for x in h))
        if n >= 2:
            return PRODUCT_XRAY, f"product-level Xray export ({n} market columns)", h
        return UNKNOWN, "has ASIN + title but too few product-market columns", h
    return UNKNOWN, "no ASIN + title header pair", h


def classify_folder(path):
    """Classify every spreadsheet in a folder (or a single file).
    -> list of {file, path, detected_type, reason}"""
    import glob
    if os.path.isfile(path):
        files = [path]
    else:
        files = sorted(f for f in glob.glob(os.path.join(path, "*"))
                       if f.lower().endswith((".xlsx", ".xls", ".csv")))
    out = []
    for f in files:
        t, reason, _ = detect_export_type(f)
        out.append({"file": os.path.basename(f), "path": f, "detected_type": t, "reason": reason})
    return out
